//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppOnOnOwn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stol
    {
        public int IDstol { get; set; }
        public Nullable<int> C_stol { get; set; }
        public Nullable<int> IDorder { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
