//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnOnOwn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMenu
    {
        public int IDorder { get; set; }
        public int IDmenu { get; set; }
        public int IDom { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual Order Order { get; set; }
    }
}
