//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnOnOwn
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopList
    {
        public int IDst { get; set; }
        public Nullable<int> IDmenu { get; set; }
        public string NameDish { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> IDcountry { get; set; }
        public byte[] img { get; set; }
        public string description { get; set; }
        public Nullable<int> IDtype { get; set; }
    
        public virtual menu menu { get; set; }
    }
}
